---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
    cluster: rebellion
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.7.0
          args:
            - '--path.sysfs=/host/sys'
            - '--path.rootfs=/host/root'
            - '--path.procfs=/host/proc'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
            - '--collector.netclass.ignored-devices=^(veth.*|cali.*|[a-f0-9]{15})$$'
            - '--collector.netdev.device-exclude=^(veth.*|cali.*|[a-f0-9]{15})$$'
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: sys
              mountPath: /host/sys
              readOnly: true
              mountPropagation: HostToContainer
            - name: root
              mountPath: /host/root
              readOnly: true
              mountPropagation: HostToContainer
            - name: proc
              mountPath: /host/proc
              readOnly: true
              mountPropagation: HostToContainer
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
        - name: proc
          hostPath:
            path: /proc
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  clusterIP: None
  selector:
    app: node-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100

