---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    name: apps
    istio-injection: enabled

