{
 "title": "Mimir Storage Monitoring",
 "tags": [ "mimir" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Mimir Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_request_duration_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Mimir Request Duration (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Mimir Memory Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cortex_ingester_memory_series)"
    }
   ]
  },
  {
   "title": "Samples Ingested Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_ingested_samples_total[5m]))"
    }
   ]
  }
 ]
}